name: macos_window_utils
description:
  macos_window_utils is a Flutter package that provides a set of methods for
  modifying the NSWindow of a Flutter application on macOS.
version: 1.9.0
repository: https://github.com/Adrian-Samoticha/macos_window_utils.dart

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.27.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

# The following section is specific to Flutter.
flutter:
  # This section identifies this Flutter project as a plugin project.
  # The 'pluginClass' and Android 'package' identifiers should not ordinarily
  # be modified. They are used by the tooling to maintain consistency when
  # adding or updating assets for this project.
  plugin:
    platforms:
      macos:
        pluginClass: MacOSWindowUtilsPlugin